<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="madConfigDsl"
    nsURI="http://www.sysord.com/mad/configuration/MadConfigDsl" nsPrefix="madConfigDsl">
  <eClassifiers xsi:type="ecore:EClass" name="MADConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configElements" upperBound="-1"
        eType="#//MADConfigElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDescriptorMdsl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyTypeMdsl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyName" eType="#//PropertyTypeMdsl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyValue" eType="#//PropertyValueMdsl"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValueMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="#//PropValueExprFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropValueExprFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteraPropValueExprFragment" eSuperTypes="#//PropValueExprFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IconDescriptorMdsl" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleDescriptor" eType="#//ClassDescriptorMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="I18NBundleMdsl" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundleDescriptor" eType="#//ClassDescriptorMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForeignModelMdsl" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//ModelProviderMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="synchronizerFactoryClass"
        eType="#//ClassDescriptorMdsl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionManagerClass"
        eType="#//ClassDescriptorMdsl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dslReference" eType="#//XtextLanguageReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relocatorQuery" eType="#//QueryMdsl"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelProviderMdsl"/>
  <eClassifiers xsi:type="ecore:EClass" name="URIExtensionModelProviderMdsl" eSuperTypes="#//ModelProviderMdsl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URIModelProviderMdsl" eSuperTypes="#//ModelProviderMdsl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomModelProviderMdsl" eSuperTypes="#//ModelProviderMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDescriptor" eType="#//ClassDescriptorMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XtextLanguageDescriptorMdsl" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activatorClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XtextLanguageReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xtextLanguageDescriptor"
        eType="#//XtextLanguageDescriptorMdsl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryEvaluatorMdsl" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDescriptor" eType="#//ClassDescriptorMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryPropertiesTypes" upperBound="-1"
        eType="#//PropertyTypeMdsl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extQServiceClassDescriptor"
        eType="#//ClassDescriptorMdsl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetType" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//WIDGET_CATEGORY_MDSL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDescriptor" eType="#//ClassDescriptorMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UITabMdsl" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i18NLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelFormatExpr" eType="#//FormatExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayerMdsl" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i18NLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelFormatExpr" eType="#//FormatExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subLayers" upperBound="-1"
        eType="#//LayerMdsl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeConfigurationMdsl" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultConfiguration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i18NLabelProvider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelProviderExpression"
        eType="#//FormatExpr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useExplicitExtends" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superConfigurations" unique="false"
        upperBound="-1" eType="#//TypeConfigurationMdsl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateElements" upperBound="-1"
        eType="#//TypeConfigurationTemplateElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutDefined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutElements" unique="false"
        upperBound="-1" eType="#//WidgetConfigurationMdsl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeConfigurationTemplateElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueQuery" eType="#//QueryUsage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeTemplateElementMdsl" eSuperTypes="#//TypeConfigurationTemplateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refIncludedTemplate" eType="#//TypeConfigurationMdsl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VALUE_CONVERTER_CATEGORY_MDSL">
    <eLiterals name="DATE" literal="DATE"/>
    <eLiterals name="DATETIME" value="1" literal="DATETIME"/>
    <eLiterals name="INTEGER" value="2" literal="INTEGER"/>
    <eLiterals name="FLOAT" value="3" literal="FLOAT"/>
    <eLiterals name="DOUBLE" value="4" literal="DOUBLE"/>
    <eLiterals name="XTEXT" value="5" literal="XTEXT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueConverter"/>
  <eClassifiers xsi:type="ecore:EClass" name="QueryBasedValueConverter" eSuperTypes="#//ValueConverter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="converterQuery" eType="#//QueryUsage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicTypeValueConverter" eSuperTypes="#//ValueConverter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//VALUE_CONVERTER_CATEGORY_MDSL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WIDGET_CATEGORY_MDSL">
    <eLiterals name="OUTPUTTEXT_WIDGET" literal="OUTPUTTEXT_WIDGET"/>
    <eLiterals name="NAVIGATION_WIDGET" value="1" literal="NAVIGATION_WIDGET"/>
    <eLiterals name="TEXT_WIDGET" value="2" literal="TEXT_WIDGET"/>
    <eLiterals name="BOOL_WIDGET" value="3" literal="BOOL_WIDGET"/>
    <eLiterals name="DATE_WIDGET" value="4" literal="DATE_WIDGET"/>
    <eLiterals name="NUMBER_WIDGET" value="5" literal="NUMBER_WIDGET"/>
    <eLiterals name="SINGLE_SELECT_WIDGET" value="6" literal="SINGLE_SELECT_WIDGET"/>
    <eLiterals name="MULTI_SELECT_WIDGET" value="7" literal="MULTI_SELECT_WIDGET"/>
    <eLiterals name="XTEXT_EDITOR" value="8" literal="XTEXT_EDITOR"/>
    <eLiterals name="XTEXT_TEXT_EDITOR" value="9" literal="XTEXT_TEXT_EDITOR"/>
    <eLiterals name="FLEXIBLE_WIDGET" value="10" literal="FLEXIBLE_WIDGET"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetConfigurationMdsl" eSuperTypes="#//TypeConfigurationTemplateElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiTab" eType="#//UITabMdsl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" unique="false"
        upperBound="-1" eType="#//LayerMdsl"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i18NLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//FormatExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widgetCategory" eType="#//WIDGET_CATEGORY_MDSL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetType" eType="#//WidgetType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dslReference" eType="#//XtextLanguageReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flexibleTemplate" eType="#//TypeConfigurationMdsl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visibilityQuery" eType="#//QueryMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editableQuery" eType="#//QueryMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueConverter" eType="#//ValueConverter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validators" upperBound="-1"
        eType="#//ValidatorMdsl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i18NFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueFormat" eType="#//FormatExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="candidatesQuery" eType="#//QueryUsage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i18NItemLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemLabelExpression" eType="#//FormatExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//CommandMdsl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validationQuery" eType="#//QueryUsage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i18NMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorMessageExpr" eType="#//FormatExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="COMMAND_CATEGORY_MDSL">
    <eLiterals name="UPDATE_COMMAND" literal="UPDATE_COMMAND"/>
    <eLiterals name="GLOBAL_COMMAND" value="1" literal="GLOBAL_COMMAND"/>
    <eLiterals name="ITEM_COMMAND" value="2" literal="ITEM_COMMAND"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandMdsl"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommandDeclaration" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//CommandDefinitionMdsl"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandDefinitionMdsl" eSuperTypes="#//CommandMdsl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//COMMAND_CATEGORY_MDSL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i18NLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//FormatExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="icon" eType="#//IconDescriptorMdsl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//QueryMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onActionSuccessUICommands"
        upperBound="-1" eType="#//UICommandMdsl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onActionErrorUICommands"
        upperBound="-1" eType="#//UICommandMdsl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandRefMdsl" eSuperTypes="#//CommandMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenced" eType="#//CommandDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i18NLabelOverride" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelOverride" eType="#//FormatExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UICommandMdsl"/>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayViewUICommand" eSuperTypes="#//UICommandMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//QueryUsage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReloadViewUICommand" eSuperTypes="#//UICommandMdsl"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReloadWidgetsUICommand" eSuperTypes="#//UICommandMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgetsToReload" unique="false"
        upperBound="-1" eType="#//WidgetConfigurationMdsl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryUsage"/>
  <eClassifiers xsi:type="ecore:EClass" name="QueryMdsl" eSuperTypes="#//QueryUsage"/>
  <eClassifiers xsi:type="ecore:EEnum" name="QUERY_OPTIMISATION_LEVEL">
    <eLiterals name="NONE" literal="NONE"/>
    <eLiterals name="VIEW" value="1" literal="VIEW"/>
    <eLiterals name="CONTEXT" value="2" literal="CONTEXT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryDeclaration" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//QueryDefinitionMdsl"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryDefinitionMdsl" eSuperTypes="#//QueryMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluator" eType="#//QueryEvaluatorMdsl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignModel" eType="#//ForeignModelMdsl"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextLocator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//QueryBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalQueryCall" eType="#//ExternalQueryCallMdsl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//PropertyMdsl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optimisationLevel" eType="#//QUERY_OPTIMISATION_LEVEL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralQueryFragment" eSuperTypes="#//QueryFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="#//QueryFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryRefMdsl" eSuperTypes="#//QueryMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenced" eType="#//QueryDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalQueryCallMdsl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalQuery" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryChain" eSuperTypes="#//QueryUsage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="queries" upperBound="-1"
        eType="#//QueryMdsl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormatExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="#//FormatExprFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormatExprFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralFormatExprFragment" eSuperTypes="#//FormatExprFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextMacro" eSuperTypes="#//MADConfigElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="macroValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextMacroRef" eSuperTypes="#//PropValueExprFragment #//QueryFragment #//FormatExprFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenced" eType="#//TextMacro"/>
  </eClassifiers>
</ecore:EPackage>
