/*
 * generated by Xtext
 */
package com.sysord.mad.configuration;

import org.eclipse.xtext.linking.ILinker;

import com.sysord.mad.configuration.custom.MadConfigDslLinker;
import com.sysord.mad.configuration.extension.ExternalQueryConfigurationServiceProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MadConfigDslRuntimeModule extends com.sysord.mad.configuration.AbstractMadConfigDslRuntimeModule {

	@Override
	public Class<? extends ILinker> bindILinker() {
		return MadConfigDslLinker.class;
	}

	public Class<ExternalQueryConfigurationServiceProvider> bindExternalQueryConfigurationServiceProvider() {
		return ExternalQueryConfigurationServiceProvider.class;
	}

	
}
