/*
* generated by Xtext
*/
package com.sysord.mad.configuration;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MadConfigDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.sysord.mad.configuration.ui.internal.MadConfigDslActivator.getInstance().getInjector("com.sysord.mad.configuration.MadConfigDsl");
	}
	
}
