/*
* generated by Xtext
*/
package com.sysord.mad.configuration.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MadConfigDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
