/*
 * generated by Xtext
 */
package com.sysord.mad.configuration.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MadConfigDslUiModule extends com.sysord.mad.configuration.ui.AbstractMadConfigDslUiModule {
	public MadConfigDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
