/*
* generated by Xtext
*/
package com.sysord.mad.configuration.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.sysord.mad.configuration.services.MadConfigDslGrammarAccess;

public class MadConfigDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MadConfigDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.sysord.mad.configuration.parser.antlr.internal.InternalMadConfigDslParser createParser(XtextTokenStream stream) {
		return new com.sysord.mad.configuration.parser.antlr.internal.InternalMadConfigDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "MADConfiguration";
	}
	
	public MadConfigDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MadConfigDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
