/*
* generated by Xtext
*/
package com.sysord.mad.configuration.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MadConfigDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/sysord/mad/configuration/parser/antlr/internal/InternalMadConfigDsl.tokens");
	}
}
